### ISSUE TITLE
exercise 7

### ISSUE THREAD

**Issue by uranium93** [mdevils/typescript-exercises#13]
**hope all safe**
I was able to resolve exercise 7 using Omit
but I am trying to resolve it in a different way using Exclude

`type PowerUser = Exclude<User, 'type'> & Exclude<Admin, 'type'> & { type: 'userType' }`

and this throwing error that :

`Type '"powerUser"' is not assignable to type '"user" | "admin"'.ts(2322)
index.ts(31, 5): The expected type comes from property 'type' which is declared here on type 'Person'`

anyone can help to understand why type:'powerUser' in not in PowerUser type
thanks

**Comment by mdevils** [comment]
Hello @uranium93, there is a difference between `Omit<T, K>` and `Exclude<U1, U2>`. `Omit` removes keys from the provided object while `Exclude` removes elements from a union.

```typescript
type User = { name: string; age: number; };
type UserWithoutAge1 = Omit<User, 'age'>;
type UserWithoutAge2 = Pick<User, Exclude<keyof User, 'age'>>;
```

**Comment by uranium93** [comment]
Hi @mdevils thanks a lot, it makes sense now
