### ISSUE TITLE
Exercise 13: $text 'WILL' should not match 'Willis'

### ISSUE THREAD

**Issue by fabb** [mdevils/typescript-exercises#18]
It confused me a bit that `Bruce Willis` (_id 2) should not be matched by the query `{ $text: 'WILL'}`. Maybe the comment for `$text` should be clarified a little that only full words should be matched.

**Comment by mdevils** [comment]
Hello @fabb, thank you for the feedback. I thought it was clearly described here: https://github.com/mdevils/typescript-exercises/blob/master/exercises/exercise-13/index.ts#L94-L96

**Comment by fabb** [comment]
Ok I read over the `finding words` part, thx.

**Comment by mdevils** [comment]
You are welcome.
