### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by meatnordrink** [mdevils/typescript-exercises#23]
Thanks so much for these exercises! They're really useful. 

I'd love if there were suggested solutions somewhere. I'm moderately experienced in Typescript, but self-taught; even if I can find a solution to the exercise, I often wonder if there's a "better way." It would be interesting to see the solution you came up with for the exercises.

Thank you again.

**Comment by snsie** [comment]
This repo contains a 'solutions' branch with answers to each question. They're very helpful!

**Comment by meatnordrink** [comment]
Oh, that's perfect! Thank you so much, @snsie !
