### ISSUE TITLE
Exercice 10-11: it's possible to provide awful type declarations

### ISSUE THREAD

**Issue by Axnyff** [mdevils/typescript-exercises#3]
Hello,
I'm currently doing the exercises and loving it!

I however noticed a way to "hack" exercise 11, I can declare my module as such

    declare module 'stats' {
      const getMaxIndex: Function;
      const getMinIndex: Function;
      const getMaxElement: Function;
      const getMinIndex: Function;
      const getMinElement: Function;
      const getMedianIndex: Function;
      const getMedianElement: Function;
      const getAverageValue: Function;
    }

I'm not sure there's a way to prevent this or should be unallowed in the rules.

Thanks for your time

**Comment by mdevils** [comment]
Hello Axnyff. Thank for noticing this. Using `any` would also hack it. No idea how to prevent it though.

**Comment by b-wils** [comment]
I'm wondering if a lint rule could be added as part of the run command to detect (and fail) on this.

Lots of good typescript lint rules, including disallowing `any`.

I haven't worked through all the exercises so not sure if it would interfere with some of them.
