### ISSUE TITLE
Exercise 7 typing issue

### ISSUE THREAD

**Issue by hanneswidrig** [mdevils/typescript-exercises#8]
## My solution:
```
type PowerUser = Omit<User, "type"> &
  Omit<Admin, "type"> & { type: "powerUser" };
```

## Official solution:
```
type PowerUser = Omit<User & Admin, 'type'> & {
    type: 'powerUser'
};
```

TypeScript 3.9 made changes to advanced types and the official solution will error out on >=3.9. I'd suggest the solutions branch to utilize this new recommendation.

**Comment by mdevils** [comment]
Thanks, I'll consider this change.
